/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.DbArticle;
import jooq.tables.DbBlogUser;
import jooq.tables.DbPermission;
import jooq.tables.DbRole;
import jooq.tables.DbRolesPermissions;
import jooq.tables.DbUserRoles;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbPublic extends SchemaImpl {

    private static final long serialVersionUID = -1002049610;

    /**
     * The reference instance of <code>public</code>
     */
    public static final DbPublic PUBLIC = new DbPublic();

    /**
     * The table <code>public.article</code>.
     */
    public final DbArticle ARTICLE = DbArticle.ARTICLE;

    /**
     * The table <code>public.blog_user</code>.
     */
    public final DbBlogUser BLOG_USER = DbBlogUser.BLOG_USER;

    /**
     * The table <code>public.permission</code>.
     */
    public final DbPermission PERMISSION = DbPermission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public final DbRole ROLE = DbRole.ROLE;

    /**
     * The table <code>public.roles_permissions</code>.
     */
    public final DbRolesPermissions ROLES_PERMISSIONS = DbRolesPermissions.ROLES_PERMISSIONS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final DbUserRoles USER_ROLES = DbUserRoles.USER_ROLES;

    /**
     * No further instances allowed
     */
    private DbPublic() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DbArticle.ARTICLE,
            DbBlogUser.BLOG_USER,
            DbPermission.PERMISSION,
            DbRole.ROLE,
            DbRolesPermissions.ROLES_PERMISSIONS,
            DbUserRoles.USER_ROLES);
    }
}
