/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.DbArticle;
import jooq.tables.Permission;
import jooq.tables.Role;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLE_ID_UINDEX = Indexes0.ARTICLE_ID_UINDEX;
    public static final Index PERMISSION_ID_UINDEX = Indexes0.PERMISSION_ID_UINDEX;
    public static final Index ROLE_ID_UINDEX = Indexes0.ROLE_ID_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARTICLE_ID_UINDEX = Internal.createIndex("article_id_uindex", DbArticle.DB_ARTICLE, new OrderField[] { DbArticle.DB_ARTICLE.ID }, true);
        public static Index PERMISSION_ID_UINDEX = Internal.createIndex("permission_id_uindex", Permission.PERMISSION, new OrderField[] { Permission.PERMISSION.ID }, true);
        public static Index ROLE_ID_UINDEX = Internal.createIndex("role_id_uindex", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
    }
}
