/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.DbArticle;
import jooq.tables.DbUser;
import jooq.tables.Permission;
import jooq.tables.Role;
import jooq.tables.RolesPermissions;
import jooq.tables.UserRoles;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -910642156;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.db_article</code>.
     */
    public final DbArticle DB_ARTICLE = DbArticle.DB_ARTICLE;

    /**
     * The table <code>public.db_user</code>.
     */
    public final DbUser DB_USER = DbUser.DB_USER;

    /**
     * The table <code>public.permission</code>.
     */
    public final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.roles_permissions</code>.
     */
    public final RolesPermissions ROLES_PERMISSIONS = RolesPermissions.ROLES_PERMISSIONS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DbArticle.DB_ARTICLE,
            DbUser.DB_USER,
            Permission.PERMISSION,
            Role.ROLE,
            RolesPermissions.ROLES_PERMISSIONS,
            UserRoles.USER_ROLES);
    }
}
