/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.DbArticle;
import jooq.tables.DbArticleComment;
import jooq.tables.DbBlogUser;
import jooq.tables.DbPermission;
import jooq.tables.DbRole;
import jooq.tables.DbRolesPermissions;
import jooq.tables.DbUserRoles;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.article</code>.
     */
    public static final DbArticle ARTICLE = DbArticle.ARTICLE;

    /**
     * The table <code>public.article_comment</code>.
     */
    public static final DbArticleComment ARTICLE_COMMENT = DbArticleComment.ARTICLE_COMMENT;

    /**
     * The table <code>public.blog_user</code>.
     */
    public static final DbBlogUser BLOG_USER = DbBlogUser.BLOG_USER;

    /**
     * The table <code>public.permission</code>.
     */
    public static final DbPermission PERMISSION = DbPermission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public static final DbRole ROLE = DbRole.ROLE;

    /**
     * The table <code>public.roles_permissions</code>.
     */
    public static final DbRolesPermissions ROLES_PERMISSIONS = DbRolesPermissions.ROLES_PERMISSIONS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final DbUserRoles USER_ROLES = DbUserRoles.USER_ROLES;
}
