/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.DbArticle;
import jooq.tables.DbUser;
import jooq.tables.Permission;
import jooq.tables.Role;
import jooq.tables.RolesPermissions;
import jooq.tables.UserRoles;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.db_article</code>.
     */
    public static final DbArticle DB_ARTICLE = DbArticle.DB_ARTICLE;

    /**
     * The table <code>public.db_user</code>.
     */
    public static final DbUser DB_USER = DbUser.DB_USER;

    /**
     * The table <code>public.permission</code>.
     */
    public static final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.roles_permissions</code>.
     */
    public static final RolesPermissions ROLES_PERMISSIONS = RolesPermissions.ROLES_PERMISSIONS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;
}
