/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import jooq.tables.interfaces.DbIArticleComment;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbArticleComment implements VertxPojo, DbIArticleComment {

    private static final long serialVersionUID = 377727931;

    private String         id;
    private String         content;
    private String         authorId;
    private Integer        version;
    private OffsetDateTime creationTime;
    private OffsetDateTime lastModificationTime;
    private String         articleId;

    public DbArticleComment() {}

    public DbArticleComment(DbIArticleComment value) {
        this.id = value.getId();
        this.content = value.getContent();
        this.authorId = value.getAuthorId();
        this.version = value.getVersion();
        this.creationTime = value.getCreationTime();
        this.lastModificationTime = value.getLastModificationTime();
        this.articleId = value.getArticleId();
    }

    public DbArticleComment(
        String         id,
        String         content,
        String         authorId,
        Integer        version,
        OffsetDateTime creationTime,
        OffsetDateTime lastModificationTime,
        String         articleId
    ) {
        this.id = id;
        this.content = content;
        this.authorId = authorId;
        this.version = version;
        this.creationTime = creationTime;
        this.lastModificationTime = lastModificationTime;
        this.articleId = articleId;
    }

    public DbArticleComment(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public DbArticleComment setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public DbArticleComment setContent(String content) {
        this.content = content;
        return this;
    }

    @Override
    public String getAuthorId() {
        return this.authorId;
    }

    @Override
    public DbArticleComment setAuthorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public Integer getVersion() {
        return this.version;
    }

    @Override
    public DbArticleComment setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public OffsetDateTime getCreationTime() {
        return this.creationTime;
    }

    @Override
    public DbArticleComment setCreationTime(OffsetDateTime creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    @Override
    public OffsetDateTime getLastModificationTime() {
        return this.lastModificationTime;
    }

    @Override
    public DbArticleComment setLastModificationTime(OffsetDateTime lastModificationTime) {
        this.lastModificationTime = lastModificationTime;
        return this;
    }

    @Override
    public String getArticleId() {
        return this.articleId;
    }

    @Override
    public DbArticleComment setArticleId(String articleId) {
        this.articleId = articleId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbArticleComment (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(authorId);
        sb.append(", ").append(version);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(lastModificationTime);
        sb.append(", ").append(articleId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIArticleComment from) {
        setId(from.getId());
        setContent(from.getContent());
        setAuthorId(from.getAuthorId());
        setVersion(from.getVersion());
        setCreationTime(from.getCreationTime());
        setLastModificationTime(from.getLastModificationTime());
        setArticleId(from.getArticleId());
    }

    @Override
    public <E extends DbIArticleComment> E into(E into) {
        into.from(this);
        return into;
    }
}
