/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.interfaces.IDbArticle;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbArticle implements VertxPojo, IDbArticle {

    private static final long serialVersionUID = -1393504022;

    private String  id;
    private String  title;
    private String  content;
    private String  authorId;
    private Integer version;

    public DbArticle() {}

    public DbArticle(IDbArticle value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.content = value.getContent();
        this.authorId = value.getAuthorId();
        this.version = value.getVersion();
    }

    public DbArticle(
        String  id,
        String  title,
        String  content,
        String  authorId,
        Integer version
    ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.authorId = authorId;
        this.version = version;
    }

    public DbArticle(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public DbArticle setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public DbArticle setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public DbArticle setContent(String content) {
        this.content = content;
        return this;
    }

    @Override
    public String getAuthorId() {
        return this.authorId;
    }

    @Override
    public DbArticle setAuthorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public Integer getVersion() {
        return this.version;
    }

    @Override
    public DbArticle setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbArticle (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(authorId);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDbArticle from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setAuthorId(from.getAuthorId());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IDbArticle> E into(E into) {
        into.from(this);
        return into;
    }
}
