/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import jooq.tables.interfaces.DbIArticle;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbArticle implements VertxPojo, DbIArticle {

    private static final long serialVersionUID = -1574009880;

    private String        id;
    private String        title;
    private String        content;
    private String        authorId;
    private Integer       version;
    private LocalDateTime creationTime;
    private LocalDateTime lastModificationTime;

    public DbArticle() {}

    public DbArticle(DbIArticle value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.content = value.getContent();
        this.authorId = value.getAuthorId();
        this.version = value.getVersion();
        this.creationTime = value.getCreationTime();
        this.lastModificationTime = value.getLastModificationTime();
    }

    public DbArticle(
        String        id,
        String        title,
        String        content,
        String        authorId,
        Integer       version,
        LocalDateTime creationTime,
        LocalDateTime lastModificationTime
    ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.authorId = authorId;
        this.version = version;
        this.creationTime = creationTime;
        this.lastModificationTime = lastModificationTime;
    }

    public DbArticle(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public DbArticle setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public DbArticle setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public DbArticle setContent(String content) {
        this.content = content;
        return this;
    }

    @Override
    public String getAuthorId() {
        return this.authorId;
    }

    @Override
    public DbArticle setAuthorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    @Override
    public Integer getVersion() {
        return this.version;
    }

    @Override
    public DbArticle setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    @Override
    public DbArticle setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    @Override
    public LocalDateTime getLastModificationTime() {
        return this.lastModificationTime;
    }

    @Override
    public DbArticle setLastModificationTime(LocalDateTime lastModificationTime) {
        this.lastModificationTime = lastModificationTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbArticle (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(authorId);
        sb.append(", ").append(version);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(lastModificationTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIArticle from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setAuthorId(from.getAuthorId());
        setVersion(from.getVersion());
        setCreationTime(from.getCreationTime());
        setLastModificationTime(from.getLastModificationTime());
    }

    @Override
    public <E extends DbIArticle> E into(E into) {
        into.from(this);
        return into;
    }
}
