/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import jooq.tables.interfaces.DbIBlogUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbBlogUser implements VertxPojo, DbIBlogUser {

    private static final long serialVersionUID = 1689639952;

    private String         username;
    private String         password;
    private String         passwordSalt;
    private Integer        version;
    private OffsetDateTime creationTime;
    private OffsetDateTime lastModificationTime;

    public DbBlogUser() {}

    public DbBlogUser(DbIBlogUser value) {
        this.username = value.getUsername();
        this.password = value.getPassword();
        this.passwordSalt = value.getPasswordSalt();
        this.version = value.getVersion();
        this.creationTime = value.getCreationTime();
        this.lastModificationTime = value.getLastModificationTime();
    }

    public DbBlogUser(
        String         username,
        String         password,
        String         passwordSalt,
        Integer        version,
        OffsetDateTime creationTime,
        OffsetDateTime lastModificationTime
    ) {
        this.username = username;
        this.password = password;
        this.passwordSalt = passwordSalt;
        this.version = version;
        this.creationTime = creationTime;
        this.lastModificationTime = lastModificationTime;
    }

    public DbBlogUser(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public DbBlogUser setUsername(String username) {
        this.username = username;
        return this;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public DbBlogUser setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public String getPasswordSalt() {
        return this.passwordSalt;
    }

    @Override
    public DbBlogUser setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
        return this;
    }

    @Override
    public Integer getVersion() {
        return this.version;
    }

    @Override
    public DbBlogUser setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public OffsetDateTime getCreationTime() {
        return this.creationTime;
    }

    @Override
    public DbBlogUser setCreationTime(OffsetDateTime creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    @Override
    public OffsetDateTime getLastModificationTime() {
        return this.lastModificationTime;
    }

    @Override
    public DbBlogUser setLastModificationTime(OffsetDateTime lastModificationTime) {
        this.lastModificationTime = lastModificationTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbBlogUser (");

        sb.append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(passwordSalt);
        sb.append(", ").append(version);
        sb.append(", ").append(creationTime);
        sb.append(", ").append(lastModificationTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIBlogUser from) {
        setUsername(from.getUsername());
        setPassword(from.getPassword());
        setPasswordSalt(from.getPasswordSalt());
        setVersion(from.getVersion());
        setCreationTime(from.getCreationTime());
        setLastModificationTime(from.getLastModificationTime());
    }

    @Override
    public <E extends DbIBlogUser> E into(E into) {
        into.from(this);
        return into;
    }
}
