/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import jooq.tables.interfaces.DbIPermission;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbPermission implements VertxPojo, DbIPermission {

    private static final long serialVersionUID = -559646815;

    private String        id;
    private LocalDateTime lastModificationTime;
    private LocalDateTime creationTime;

    public DbPermission() {}

    public DbPermission(DbIPermission value) {
        this.id = value.getId();
        this.lastModificationTime = value.getLastModificationTime();
        this.creationTime = value.getCreationTime();
    }

    public DbPermission(
        String        id,
        LocalDateTime lastModificationTime,
        LocalDateTime creationTime
    ) {
        this.id = id;
        this.lastModificationTime = lastModificationTime;
        this.creationTime = creationTime;
    }

    public DbPermission(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public DbPermission setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public LocalDateTime getLastModificationTime() {
        return this.lastModificationTime;
    }

    @Override
    public DbPermission setLastModificationTime(LocalDateTime lastModificationTime) {
        this.lastModificationTime = lastModificationTime;
        return this;
    }

    @Override
    public LocalDateTime getCreationTime() {
        return this.creationTime;
    }

    @Override
    public DbPermission setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbPermission (");

        sb.append(id);
        sb.append(", ").append(lastModificationTime);
        sb.append(", ").append(creationTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIPermission from) {
        setId(from.getId());
        setLastModificationTime(from.getLastModificationTime());
        setCreationTime(from.getCreationTime());
    }

    @Override
    public <E extends DbIPermission> E into(E into) {
        into.from(this);
        return into;
    }
}
