/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.interfaces.DbIPermission;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbPermission implements VertxPojo, DbIPermission {

    private static final long serialVersionUID = -805591355;

    private String id;

    public DbPermission() {}

    public DbPermission(DbIPermission value) {
        this.id = value.getId();
    }

    public DbPermission(
        String id
    ) {
        this.id = id;
    }

    public DbPermission(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public DbPermission setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbPermission (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIPermission from) {
        setId(from.getId());
    }

    @Override
    public <E extends DbIPermission> E into(E into) {
        into.from(this);
        return into;
    }
}
