/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import jooq.tables.interfaces.DbIRole;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbRole implements VertxPojo, DbIRole {

    private static final long serialVersionUID = 851493581;

    private String         id;
    private OffsetDateTime lastModificationTime;
    private OffsetDateTime creationTime;

    public DbRole() {}

    public DbRole(DbIRole value) {
        this.id = value.getId();
        this.lastModificationTime = value.getLastModificationTime();
        this.creationTime = value.getCreationTime();
    }

    public DbRole(
        String         id,
        OffsetDateTime lastModificationTime,
        OffsetDateTime creationTime
    ) {
        this.id = id;
        this.lastModificationTime = lastModificationTime;
        this.creationTime = creationTime;
    }

    public DbRole(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public DbRole setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public OffsetDateTime getLastModificationTime() {
        return this.lastModificationTime;
    }

    @Override
    public DbRole setLastModificationTime(OffsetDateTime lastModificationTime) {
        this.lastModificationTime = lastModificationTime;
        return this;
    }

    @Override
    public OffsetDateTime getCreationTime() {
        return this.creationTime;
    }

    @Override
    public DbRole setCreationTime(OffsetDateTime creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbRole (");

        sb.append(id);
        sb.append(", ").append(lastModificationTime);
        sb.append(", ").append(creationTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIRole from) {
        setId(from.getId());
        setLastModificationTime(from.getLastModificationTime());
        setCreationTime(from.getCreationTime());
    }

    @Override
    public <E extends DbIRole> E into(E into) {
        into.from(this);
        return into;
    }
}
