/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.interfaces.DbIRole;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbRole implements VertxPojo, DbIRole {

    private static final long serialVersionUID = -1425052457;

    private String id;

    public DbRole() {}

    public DbRole(DbIRole value) {
        this.id = value.getId();
    }

    public DbRole(
        String id
    ) {
        this.id = id;
    }

    public DbRole(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public DbRole setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbRole (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIRole from) {
        setId(from.getId());
    }

    @Override
    public <E extends DbIRole> E into(E into) {
        into.from(this);
        return into;
    }
}
