/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.interfaces.DbIRolesPermissions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbRolesPermissions implements VertxPojo, DbIRolesPermissions {

    private static final long serialVersionUID = 2094383827;

    private String roleId;
    private String permissionId;

    public DbRolesPermissions() {}

    public DbRolesPermissions(DbIRolesPermissions value) {
        this.roleId = value.getRoleId();
        this.permissionId = value.getPermissionId();
    }

    public DbRolesPermissions(
        String roleId,
        String permissionId
    ) {
        this.roleId = roleId;
        this.permissionId = permissionId;
    }

    public DbRolesPermissions(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getRoleId() {
        return this.roleId;
    }

    @Override
    public DbRolesPermissions setRoleId(String roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public String getPermissionId() {
        return this.permissionId;
    }

    @Override
    public DbRolesPermissions setPermissionId(String permissionId) {
        this.permissionId = permissionId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbRolesPermissions (");

        sb.append(roleId);
        sb.append(", ").append(permissionId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIRolesPermissions from) {
        setRoleId(from.getRoleId());
        setPermissionId(from.getPermissionId());
    }

    @Override
    public <E extends DbIRolesPermissions> E into(E into) {
        into.from(this);
        return into;
    }
}
