/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.interfaces.IPermission;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permission implements VertxPojo, IPermission {

    private static final long serialVersionUID = -434518579;

    private String id;

    public Permission() {}

    public Permission(IPermission value) {
        this.id = value.getId();
    }

    public Permission(
        String id
    ) {
        this.id = id;
    }

    public Permission(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public Permission setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Permission (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPermission from) {
        setId(from.getId());
    }

    @Override
    public <E extends IPermission> E into(E into) {
        into.from(this);
        return into;
    }
}
