/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.interfaces.IRolesPermissions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesPermissions implements VertxPojo, IRolesPermissions {

    private static final long serialVersionUID = 68716405;

    private String roleId;
    private String permissionId;

    public RolesPermissions() {}

    public RolesPermissions(IRolesPermissions value) {
        this.roleId = value.getRoleId();
        this.permissionId = value.getPermissionId();
    }

    public RolesPermissions(
        String roleId,
        String permissionId
    ) {
        this.roleId = roleId;
        this.permissionId = permissionId;
    }

    public RolesPermissions(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getRoleId() {
        return this.roleId;
    }

    @Override
    public RolesPermissions setRoleId(String roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public String getPermissionId() {
        return this.permissionId;
    }

    @Override
    public RolesPermissions setPermissionId(String permissionId) {
        this.permissionId = permissionId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RolesPermissions (");

        sb.append(roleId);
        sb.append(", ").append(permissionId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRolesPermissions from) {
        setRoleId(from.getRoleId());
        setPermissionId(from.getPermissionId());
    }

    @Override
    public <E extends IRolesPermissions> E into(E into) {
        into.from(this);
        return into;
    }
}
