/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.interfaces.IRole;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements VertxPojo, IRole {

    private static final long serialVersionUID = -996214817;

    private String id;

    public Role() {}

    public Role(IRole value) {
        this.id = value.getId();
    }

    public Role(
        String id
    ) {
        this.id = id;
    }

    public Role(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public Role setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRole from) {
        setId(from.getId());
    }

    @Override
    public <E extends IRole> E into(E into) {
        into.from(this);
        return into;
    }
}
