/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import jooq.tables.DbArticleComment;
import jooq.tables.interfaces.DbIArticleComment;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbArticleCommentRecord extends UpdatableRecordImpl<DbArticleCommentRecord> implements VertxPojo, Record7<String, String, String, Integer, OffsetDateTime, OffsetDateTime, String>, DbIArticleComment {

    private static final long serialVersionUID = -472073049;

    /**
     * Setter for <code>public.article_comment.id</code>.
     */
    @Override
    public DbArticleCommentRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.article_comment.id</code>.
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.article_comment.content</code>.
     */
    @Override
    public DbArticleCommentRecord setContent(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.article_comment.content</code>.
     */
    @Override
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.article_comment.author_id</code>.
     */
    @Override
    public DbArticleCommentRecord setAuthorId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.article_comment.author_id</code>.
     */
    @Override
    public String getAuthorId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.article_comment.version</code>.
     */
    @Override
    public DbArticleCommentRecord setVersion(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.article_comment.version</code>.
     */
    @Override
    public Integer getVersion() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.article_comment.creation_time</code>.
     */
    @Override
    public DbArticleCommentRecord setCreationTime(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.article_comment.creation_time</code>.
     */
    @Override
    public OffsetDateTime getCreationTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.article_comment.last_modification_time</code>.
     */
    @Override
    public DbArticleCommentRecord setLastModificationTime(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.article_comment.last_modification_time</code>.
     */
    @Override
    public OffsetDateTime getLastModificationTime() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.article_comment.article_id</code>.
     */
    @Override
    public DbArticleCommentRecord setArticleId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.article_comment.article_id</code>.
     */
    @Override
    public String getArticleId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, Integer, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, Integer, OffsetDateTime, OffsetDateTime, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DbArticleComment.ARTICLE_COMMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return DbArticleComment.ARTICLE_COMMENT.CONTENT;
    }

    @Override
    public Field<String> field3() {
        return DbArticleComment.ARTICLE_COMMENT.AUTHOR_ID;
    }

    @Override
    public Field<Integer> field4() {
        return DbArticleComment.ARTICLE_COMMENT.VERSION;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return DbArticleComment.ARTICLE_COMMENT.CREATION_TIME;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return DbArticleComment.ARTICLE_COMMENT.LAST_MODIFICATION_TIME;
    }

    @Override
    public Field<String> field7() {
        return DbArticleComment.ARTICLE_COMMENT.ARTICLE_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public String component3() {
        return getAuthorId();
    }

    @Override
    public Integer component4() {
        return getVersion();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreationTime();
    }

    @Override
    public OffsetDateTime component6() {
        return getLastModificationTime();
    }

    @Override
    public String component7() {
        return getArticleId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public String value3() {
        return getAuthorId();
    }

    @Override
    public Integer value4() {
        return getVersion();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreationTime();
    }

    @Override
    public OffsetDateTime value6() {
        return getLastModificationTime();
    }

    @Override
    public String value7() {
        return getArticleId();
    }

    @Override
    public DbArticleCommentRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public DbArticleCommentRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public DbArticleCommentRecord value3(String value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public DbArticleCommentRecord value4(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public DbArticleCommentRecord value5(OffsetDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public DbArticleCommentRecord value6(OffsetDateTime value) {
        setLastModificationTime(value);
        return this;
    }

    @Override
    public DbArticleCommentRecord value7(String value) {
        setArticleId(value);
        return this;
    }

    @Override
    public DbArticleCommentRecord values(String value1, String value2, String value3, Integer value4, OffsetDateTime value5, OffsetDateTime value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIArticleComment from) {
        setId(from.getId());
        setContent(from.getContent());
        setAuthorId(from.getAuthorId());
        setVersion(from.getVersion());
        setCreationTime(from.getCreationTime());
        setLastModificationTime(from.getLastModificationTime());
        setArticleId(from.getArticleId());
    }

    @Override
    public <E extends DbIArticleComment> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbArticleCommentRecord
     */
    public DbArticleCommentRecord() {
        super(DbArticleComment.ARTICLE_COMMENT);
    }

    /**
     * Create a detached, initialised DbArticleCommentRecord
     */
    public DbArticleCommentRecord(String id, String content, String authorId, Integer version, OffsetDateTime creationTime, OffsetDateTime lastModificationTime, String articleId) {
        super(DbArticleComment.ARTICLE_COMMENT);

        set(0, id);
        set(1, content);
        set(2, authorId);
        set(3, version);
        set(4, creationTime);
        set(5, lastModificationTime);
        set(6, articleId);
    }

    public DbArticleCommentRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
