/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;

import jooq.tables.DbPermission;
import jooq.tables.interfaces.DbIPermission;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbPermissionRecord extends UpdatableRecordImpl<DbPermissionRecord> implements VertxPojo, Record3<String, LocalDateTime, LocalDateTime>, DbIPermission {

    private static final long serialVersionUID = -1399511382;

    /**
     * Setter for <code>public.permission.id</code>.
     */
    @Override
    public DbPermissionRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.permission.id</code>.
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.permission.last_modification_time</code>.
     */
    @Override
    public DbPermissionRecord setLastModificationTime(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.permission.last_modification_time</code>.
     */
    @Override
    public LocalDateTime getLastModificationTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.permission.creation_time</code>.
     */
    @Override
    public DbPermissionRecord setCreationTime(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.permission.creation_time</code>.
     */
    @Override
    public LocalDateTime getCreationTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DbPermission.PERMISSION.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return DbPermission.PERMISSION.LAST_MODIFICATION_TIME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return DbPermission.PERMISSION.CREATION_TIME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getLastModificationTime();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTime();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getLastModificationTime();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTime();
    }

    @Override
    public DbPermissionRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public DbPermissionRecord value2(LocalDateTime value) {
        setLastModificationTime(value);
        return this;
    }

    @Override
    public DbPermissionRecord value3(LocalDateTime value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public DbPermissionRecord values(String value1, LocalDateTime value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIPermission from) {
        setId(from.getId());
        setLastModificationTime(from.getLastModificationTime());
        setCreationTime(from.getCreationTime());
    }

    @Override
    public <E extends DbIPermission> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbPermissionRecord
     */
    public DbPermissionRecord() {
        super(DbPermission.PERMISSION);
    }

    /**
     * Create a detached, initialised DbPermissionRecord
     */
    public DbPermissionRecord(String id, LocalDateTime lastModificationTime, LocalDateTime creationTime) {
        super(DbPermission.PERMISSION);

        set(0, id);
        set(1, lastModificationTime);
        set(2, creationTime);
    }

    public DbPermissionRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
