/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import jooq.tables.DbRole;
import jooq.tables.interfaces.DbIRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbRoleRecord extends UpdatableRecordImpl<DbRoleRecord> implements VertxPojo, Record1<String>, DbIRole {

    private static final long serialVersionUID = -1103881902;

    /**
     * Setter for <code>public.role.id</code>.
     */
    @Override
    public DbRoleRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.role.id</code>.
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DbRole.ROLE.ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public DbRoleRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public DbRoleRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(DbIRole from) {
        setId(from.getId());
    }

    @Override
    public <E extends DbIRole> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbRoleRecord
     */
    public DbRoleRecord() {
        super(DbRole.ROLE);
    }

    /**
     * Create a detached, initialised DbRoleRecord
     */
    public DbRoleRecord(String id) {
        super(DbRole.ROLE);

        set(0, id);
    }

    public DbRoleRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
