/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.util.Arrays;
import java.util.List;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.DbUserRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbUser extends TableImpl<DbUserRecord> {

    private static final long serialVersionUID = 1480281737;

    /**
     * The reference instance of <code>public.db_user</code>
     */
    public static final DbUser DB_USER = new DbUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DbUserRecord> getRecordType() {
        return DbUserRecord.class;
    }

    /**
     * The column <code>public.db_user.username</code>.
     */
    public final TableField<DbUserRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.db_user.password</code>.
     */
    public final TableField<DbUserRecord, String> PASSWORD = createField(DSL.name("password"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.db_user.password_salt</code>.
     */
    public final TableField<DbUserRecord, String> PASSWORD_SALT = createField(DSL.name("password_salt"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.db_user.version</code>.
     */
    public final TableField<DbUserRecord, Integer> VERSION = createField(DSL.name("version"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.db_user</code> table reference
     */
    public DbUser() {
        this(DSL.name("db_user"), null);
    }

    /**
     * Create an aliased <code>public.db_user</code> table reference
     */
    public DbUser(String alias) {
        this(DSL.name(alias), DB_USER);
    }

    /**
     * Create an aliased <code>public.db_user</code> table reference
     */
    public DbUser(Name alias) {
        this(alias, DB_USER);
    }

    private DbUser(Name alias, Table<DbUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private DbUser(Name alias, Table<DbUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> DbUser(Table<O> child, ForeignKey<O, DbUserRecord> key) {
        super(child, key, DB_USER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<DbUserRecord> getPrimaryKey() {
        return Keys.PK_USERNAME;
    }

    @Override
    public List<UniqueKey<DbUserRecord>> getKeys() {
        return Arrays.<UniqueKey<DbUserRecord>>asList(Keys.PK_USERNAME);
    }

    @Override
    public DbUser as(String alias) {
        return new DbUser(DSL.name(alias), this);
    }

    @Override
    public DbUser as(Name alias) {
        return new DbUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DbUser rename(String name) {
        return new DbUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DbUser rename(Name name) {
        return new DbUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
