/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.time.LocalDateTime;
import java.util.Collection;

import jooq.tables.DbPermission;
import jooq.tables.records.DbPermissionRecord;

import org.jooq.Configuration;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbPermissionDao extends AbstractReactiveVertxDAO<DbPermissionRecord, jooq.tables.pojos.DbPermission, String, Future<List<jooq.tables.pojos.DbPermission>>, Future<jooq.tables.pojos.DbPermission>, Future<Integer>, Future<String>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<DbPermissionRecord,jooq.tables.pojos.DbPermission,String> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public DbPermissionDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
        super(DbPermission.PERMISSION, jooq.tables.pojos.DbPermission.class, new ReactiveClassicQueryExecutor<DbPermissionRecord,jooq.tables.pojos.DbPermission,String>(configuration,delegate,jooq.tables.mappers.RowMappers.getDbPermissionMapper()));
    }

    @Override
    protected String getId(jooq.tables.pojos.DbPermission object) {
        return object.getId();
    }

    /**
     * Find records that have <code>last_modification_time IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.DbPermission>> findManyByDbLastModificationTime(Collection<LocalDateTime> values) {
        return findManyByCondition(DbPermission.PERMISSION.LAST_MODIFICATION_TIME.in(values));
    }

    /**
     * Find records that have <code>last_modification_time IN (values)</code> asynchronously limited by the given limit
     */
    public Future<List<jooq.tables.pojos.DbPermission>> findManyByDbLastModificationTime(Collection<LocalDateTime> values, int limit) {
        return findManyByCondition(DbPermission.PERMISSION.LAST_MODIFICATION_TIME.in(values),limit);
    }

    /**
     * Find records that have <code>creation_time IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.DbPermission>> findManyByDbCreationTime(Collection<LocalDateTime> values) {
        return findManyByCondition(DbPermission.PERMISSION.CREATION_TIME.in(values));
    }

    /**
     * Find records that have <code>creation_time IN (values)</code> asynchronously limited by the given limit
     */
    public Future<List<jooq.tables.pojos.DbPermission>> findManyByDbCreationTime(Collection<LocalDateTime> values, int limit) {
        return findManyByCondition(DbPermission.PERMISSION.CREATION_TIME.in(values),limit);
    }

    @Override
    public ReactiveClassicQueryExecutor<DbPermissionRecord,jooq.tables.pojos.DbPermission,String> queryExecutor(){
        return (ReactiveClassicQueryExecutor<DbPermissionRecord,jooq.tables.pojos.DbPermission,String>) super.queryExecutor();
    }
}
