/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import jooq.tables.Role;
import jooq.tables.records.RoleRecord;

import org.jooq.Configuration;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleDao extends AbstractReactiveVertxDAO<RoleRecord, jooq.tables.pojos.Role, String, Future<List<jooq.tables.pojos.Role>>, Future<jooq.tables.pojos.Role>, Future<Integer>, Future<String>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<RoleRecord,jooq.tables.pojos.Role,String> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public RoleDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
        super(Role.ROLE, jooq.tables.pojos.Role.class, new ReactiveClassicQueryExecutor<RoleRecord,jooq.tables.pojos.Role,String>(configuration,delegate,jooq.tables.mappers.RowMappers.getRoleMapper()));
    }

    @Override
    protected String getId(jooq.tables.pojos.Role object) {
        return object.getId();
    }

    @Override
    public ReactiveClassicQueryExecutor<RoleRecord,jooq.tables.pojos.Role,String> queryExecutor(){
        return (ReactiveClassicQueryExecutor<RoleRecord,jooq.tables.pojos.Role,String>) super.queryExecutor();
    }
}
