/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface DbIArticle extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.article.id</code>.
     */
    public DbIArticle setId(String value);

    /**
     * Getter for <code>public.article.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>public.article.title</code>.
     */
    public DbIArticle setTitle(String value);

    /**
     * Getter for <code>public.article.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>public.article.content</code>.
     */
    public DbIArticle setContent(String value);

    /**
     * Getter for <code>public.article.content</code>.
     */
    public String getContent();

    /**
     * Setter for <code>public.article.author_id</code>.
     */
    public DbIArticle setAuthorId(String value);

    /**
     * Getter for <code>public.article.author_id</code>.
     */
    public String getAuthorId();

    /**
     * Setter for <code>public.article.version</code>.
     */
    public DbIArticle setVersion(Integer value);

    /**
     * Getter for <code>public.article.version</code>.
     */
    public Integer getVersion();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface DbIArticle
     */
    public void from(DbIArticle from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface DbIArticle
     */
    public <E extends DbIArticle> E into(E into);

    @Override
    public default DbIArticle fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getString("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.String",e);
        }
        try {
            setTitle(json.getString("title"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("title","java.lang.String",e);
        }
        try {
            setContent(json.getString("content"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("content","java.lang.String",e);
        }
        try {
            setAuthorId(json.getString("author_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("author_id","java.lang.String",e);
        }
        try {
            setVersion(json.getInteger("version"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("version","java.lang.Integer",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("title",getTitle());
        json.put("content",getContent());
        json.put("author_id",getAuthorId());
        json.put("version",getVersion());
        return json;
    }

}
