/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface DbIBlogUser extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.blog_user.username</code>.
     */
    public DbIBlogUser setUsername(String value);

    /**
     * Getter for <code>public.blog_user.username</code>.
     */
    public String getUsername();

    /**
     * Setter for <code>public.blog_user.password</code>.
     */
    public DbIBlogUser setPassword(String value);

    /**
     * Getter for <code>public.blog_user.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>public.blog_user.password_salt</code>.
     */
    public DbIBlogUser setPasswordSalt(String value);

    /**
     * Getter for <code>public.blog_user.password_salt</code>.
     */
    public String getPasswordSalt();

    /**
     * Setter for <code>public.blog_user.version</code>.
     */
    public DbIBlogUser setVersion(Integer value);

    /**
     * Getter for <code>public.blog_user.version</code>.
     */
    public Integer getVersion();

    /**
     * Setter for <code>public.blog_user.creation_time</code>.
     */
    public DbIBlogUser setCreationTime(OffsetDateTime value);

    /**
     * Getter for <code>public.blog_user.creation_time</code>.
     */
    public OffsetDateTime getCreationTime();

    /**
     * Setter for <code>public.blog_user.last_modification_time</code>.
     */
    public DbIBlogUser setLastModificationTime(OffsetDateTime value);

    /**
     * Getter for <code>public.blog_user.last_modification_time</code>.
     */
    public OffsetDateTime getLastModificationTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface DbIBlogUser
     */
    public void from(DbIBlogUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface DbIBlogUser
     */
    public <E extends DbIBlogUser> E into(E into);

    @Override
    public default DbIBlogUser fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setUsername(json.getString("username"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("username","java.lang.String",e);
        }
        try {
            setPassword(json.getString("password"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("password","java.lang.String",e);
        }
        try {
            setPasswordSalt(json.getString("password_salt"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("password_salt","java.lang.String",e);
        }
        try {
            setVersion(json.getInteger("version"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("version","java.lang.Integer",e);
        }
        try {
            String creation_timeString = json.getString("creation_time");
            setCreationTime(creation_timeString == null?null:java.time.OffsetDateTime.parse(creation_timeString));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("creation_time","java.time.OffsetDateTime",e);
        }
        try {
            String last_modification_timeString = json.getString("last_modification_time");
            setLastModificationTime(last_modification_timeString == null?null:java.time.OffsetDateTime.parse(last_modification_timeString));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("last_modification_time","java.time.OffsetDateTime",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("username",getUsername());
        json.put("password",getPassword());
        json.put("password_salt",getPasswordSalt());
        json.put("version",getVersion());
        json.put("creation_time",getCreationTime()==null?null:getCreationTime().toString());
        json.put("last_modification_time",getLastModificationTime()==null?null:getLastModificationTime().toString());
        return json;
    }

}
