/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserRoles extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.user_roles.username</code>.
     */
    public IUserRoles setUsername(String value);

    /**
     * Getter for <code>public.user_roles.username</code>.
     */
    public String getUsername();

    /**
     * Setter for <code>public.user_roles.role</code>.
     */
    public IUserRoles setRole(String value);

    /**
     * Getter for <code>public.user_roles.role</code>.
     */
    public String getRole();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserRoles
     */
    public void from(IUserRoles from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserRoles
     */
    public <E extends IUserRoles> E into(E into);

    @Override
    public default IUserRoles fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setUsername(json.getString("username"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("username","java.lang.String",e);
        }
        try {
            setRole(json.getString("role"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("role","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("username",getUsername());
        json.put("role",getRole());
        return json;
    }

}
